server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/testmicro_db
    username: root
    password: 1234

  security:
    user:
      name: foptun
      password: 1234

